Booking_Hotel_QNT/Booking_Hotel_QNT/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
   path('', include('hotel.urls')),
    path('admin/', admin.site.urls),
]

Booking_Hotel_QNT/hotel/urls.py
from django.urls import path
from .views import indexView,galleryView,asView,bookingView,failedView,blogView,loginView,resView,logoutView
from . import views
app_name="hotel"

urlpatterns = [
   path('', indexView.as_view(),name="index"),
   path('gallery/', galleryView.as_view(), name="gallery"),
   path('as/', asView.as_view(), name="as"),
   path('booking/', bookingView.as_view(), name="booking"),
   path('404page/', failedView.as_view(), name="404"),
   path('blog/', blogView.as_view(), name="blog"),
   path('login/',loginView.as_view(),name="login"),
   path('res/',resView.as_view(),name="res"),
   path('logout/',logoutView.as_view(),name="logout"),
]

Booking_Hotel_QNT/chitietbooking/models.py
from django.db import models
from khachhang.models import MyUser
from phong.models import Phong
from django.utils import timezone
# Create your models here.
class ChiTietBooking(models.Model):
    mabooking= models.AutoField(primary_key=True)
    tendn= models.ForeignKey(MyUser, on_delete=models.CASCADE)
    sophong= models.ForeignKey(Phong, on_delete=models.CASCADE,default=0)
    ngaynhanphong= models.DateTimeField(default= timezone.now)
    ngaytratphong= models.DateTimeField(default= timezone.now)
    thanhtien=models.BigIntegerField(default=0)

Booking_Hotel_QNT/hotel/models.py
from django.db import models

# Create your models here.

Booking_Hotel_QNT/khachhang/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
# Create your models here.
class MyUser(AbstractUser):
    tendn = AbstractUser.username
    sdt=models.CharField(default='',max_length=11)
    
    

Booking_Hotel_QNT/phong/models.py
from django.db import models

# Create your models here.

class Phong(models.Model):
    choice_phong = {(0,"Standard Room"),(1,"Superior Room"),(2,"Deluxe Room"),(3,"Suite Room")
                    ,(4,"Executive Suite Room"),(5,"President Suite Room"),(6,"Adjacent Rooms"),(7,"Hollywood Twin Room")}
    sophong= models.CharField(max_length=30,primary_key=True,default=0)
    loaiphong = models.IntegerField(choices = choice_phong,default=0)
    gia= models.BigIntegerField(default=0)
    active = models.BooleanField(default = False)
    
    def __str__(self):
        return self.sophong

Booking_Hotel_QNT/hotel/forms.py
from django import forms
from phong.models import Phong
from chitietbooking.models import ChiTietBooking
from khachhang.models import MyUser
from django.forms import ModelForm
from django.contrib.auth.forms import UserCreationForm
class formPhong(ModelForm):
    class Meta:
        model=Phong
        fields=['sophong','loaiphong','gia']
        labels= {'sophong':'So Phong'}
class formPhong(ModelForm):
    class Meta:
        model=Phong
        fields=['sophong','loaiphong','gia']
        labels= {'sophong':'So Phong'}
class SignUpForm(UserCreationForm):
#     first_name = forms.CharField(max_length=30, required=False, help_text='Optional.')
#     last_name = forms.CharField(max_length=30, required=False, help_text='Optional.')
#     email = forms.EmailField(max_length=254, help_text='Required. Inform a valid email address.')
    class Meta:
        model = MyUser
        fields = ('username', 'password1','password2','email','sdt')
class formCTBK(ModelForm):
    class Meta:
        model=ChiTietBooking
        fields=['mabooking','tendn','sophong']
        labels= {'sophong':'So Phong'}
        
        
        
        

Booking_Hotel_QNT/chitietbooking/views.py
from django.shortcuts import render

# Create your views here.

Booking_Hotel_QNT/hotel/views.py
from django.shortcuts import render,redirect
from chitietbooking.models import ChiTietBooking
from django.views import View
from .forms import SignUpForm,formCTBK
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth import authenticate, login,get_user_model, logout
from django.contrib.auth.forms import UserCreationForm
from phong.models import Phong
from khachhang.models import MyUser
# Create your views here.

class indexView(LoginRequiredMixin, View):
    login_url="/login/"
    def get(self,request):
        form = Phong.objects.all()
        context = {'f':form}
        return render(request, 'hoteltp/index.html',context)
    def post(self,request):
        sp = request.POST.get('sp')
        f = Phong.objects.get(sophong=sp)
#         f.active = True
#         f.save()
#         form = Phong.objects.all()
#         context = {'f':form}
        context = {'f' : f}
        return render(request, 'hoteltp/booking.html',context)
class galleryView(LoginRequiredMixin,View):
    login_url="/login/"
    def get(self,request):
        return render(request, 'hoteltp/gallery.html')
    
class asView(LoginRequiredMixin,View):
    login_url="/login/"
    def get(self,request):
        return render(request, 'hoteltp/about-us.html')

class bookingView(LoginRequiredMixin,View):
    login_url="/login/"
    def get(self,request):
        form=ChiTietBooking.objects.all()
        context={"h":form}
        return render(request, 'hoteltp/booking.html',context)
    def post(self,request):
        mbk=request.POST.get("mabk")
        if mbk is None:
            sp = request.POST.get("sp")
            tentk = request.POST.get("tentk")
            dt = request.POST.get("dt")
            a = MyUser.objects.get(username=tentk)
            f = Phong.objects.get(sophong=sp)
            f.active = True
            f.save()
            f3 = ChiTietBooking(tendn=a,sophong=f,thanhtien=f.gia,ngaynhanphong=dt)
            f3.save()
            formc = ChiTietBooking.objects.all()
            formp = Phong.objects.all()
#             context = {'f':formp,'h':formc}
            context = {'h':formc}
            return render(request,'hoteltp/booking.html',context)
        else:
            sp1=request.POST.get("sp1")
            f = Phong.objects.get(sophong=sp1)
            formc = ChiTietBooking.objects.all()
            f.active = False
            f.save()
            f3 = ChiTietBooking(mabooking=mbk)
            f3.delete()
            formp = Phong.objects.all()
            context = {'f':formp,'h':formc}
            return render(request,'hoteltp/booking.html',context)
        
class failedView(LoginRequiredMixin,View):
    login_url="/login/"
    def get(self,request):
        return render(request, 'hoteltp/404.html')
    
class blogView(LoginRequiredMixin,View):
    login_url="/login/"
    def get(self,request):
        return render(request, 'hoteltp/blog.html')    
class loginView(View):
    login_url="/login/"
    def get(self,request):
        return render(request, 'hoteltp/login.html')
    def post(self, request):
        tk = request.POST.get('un')
        mk = request.POST.get('pass')
        my_user = authenticate(username=tk,password=mk)
        if(my_user is None):
            el = "Tài khoản hoặc mật khẩu không đúng"
            return render(request, 'hoteltp/login.html',{'el':el})
        else:
            login(request, my_user)
#             return render(request, 'hoteltp/index.html')
            return redirect('hotel:index')
class resView(View):
    def get(self,request):
        form = SignUpForm()
        context = {'form': form}
        return render(request, 'hoteltp/res.html', context)   
    def post(self,request):
        dki = SignUpForm(request.POST)
        if(dki.is_valid()):
            dki.save()
            tk = request.POST.get('username')
            mk = request.POST.get('password1')
            my_user = authenticate(username=tk,password=mk)
            login(request, my_user)
            
#             return render(request,'hoteltp/index.html')
            return redirect('hotel:index')
        else:
            form = SignUpForm()
            kt = "Đăng kí thất bại!"
            context = {'form': form,'kt':kt}
            return render(request,'hoteltp/res.html',context)
class logoutView(View):
    def get(self,request):
        logout(request)
        return redirect('hotel:login')     

Booking_Hotel_QNT/khachhang/views.py
from django.shortcuts import render

# Create your views here.

Booking_Hotel_QNT/phong/views.py
from django.shortcuts import render

# Create your views here.

Booking_Hotel_QNT/templates/hoteltp/base.html
<!DOCTYPE html>
<html>
<!-- Added by HTTrack --><meta http-equiv="content-type" content="text/html;charset=UTF-8" /><!-- /Added by HTTrack -->
<head>
	<link href="https://fonts.googleapis.com/css?family=Pacifico&display=swap&subset=vietnamese" rel="stylesheet">
	<link href="https://fonts.googleapis.com/css?family=Fira+Sans&display=swap" rel="stylesheet">
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Hotel Booking</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
   	{% include 'hoteltp/filecss.html' %}
</head>
{% block body %}

{% endblock %}

{% include 'hoteltp/filefooter.html' %}
</html>

Booking_Hotel_QNT/templates/hoteltp/filecss.html
{% load static %}
		<link rel="icon" href="{% static 'hoteltp/img/favicon.ico' %}" sizes="16x16">
        <!-- fonts -->
		<link href='http://fonts.googleapis.com/css?family=Playfair+Display:400,700,900' rel='stylesheet' type='text/css'>
        <link href='http://fonts.googleapis.com/css?family=Karla:700,400' rel='stylesheet' type='text/css'>
        <link href='http://fonts.googleapis.com/css?family=Lora:400,700' rel='stylesheet' type='text/css'>

        <!-- fontawesome -->
		<link rel="stylesheet" href="{% static 'hoteltp/css/font-awesome.css' %}" />

        <!-- bootstrap -->
		<link rel="stylesheet" href="{% static 'hoteltp/css/bootstrap.min.css' %}" />

        <!-- uikit -->
        <link rel="stylesheet" href="{% static 'hoteltp/css/uikit.min.css' %}" />

        <!-- animate -->
        <link rel="stylesheet" href="{% static 'hoteltp/css/animate.css' %}" />
        <link rel="stylesheet" href="{% static 'hoteltp/css/datepicker.css' %}" />
        <!-- Owl carousel 2 css -->
        <link rel="stylesheet" href="{% static 'hoteltp/css/owl.carousel.css' %}">
        <!-- rev slider -->
        <link rel="stylesheet" href="{% static 'hoteltp/css/rev-slider/settings.css' %}" />
        <!-- lightslider -->
        <link rel="stylesheet" href="{% static 'hoteltp/css/lightslider.css' %}">
        <!-- Theme -->
        <link rel="stylesheet" href="{% static 'hoteltp/css/reset.css' %}">
        
        <!-- custom css -->
		<link rel="stylesheet" href="{% static 'hoteltp/css/style.css' %}" />
        <!-- responsive -->
		<link rel="stylesheet" href="{% static 'hoteltp/css/responsive.css' %}" />

        <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
        <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
        <!-- This Template Is Fully Coded By Aftab Zaman from swiftconcept.com -->
        <!--[if lt IE 9]>
          <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
          <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
        <![endif]-->

Booking_Hotel_QNT/templates/hoteltp/filefooter.html
{% load static %}
	<!-- start contact us area -->
        <section class="contact_us_area content-left">
            <div class="container">
                <div class="contact_us clearfix">
                    <div class="col-lg-3 col-md-3 col-sm-3 col-xs-12">
                        <div class="call clearfix">
                            <h6>Call Us</h6>
                            <p>012 345 6789</p>
                        </div>
                    </div>
                    <div class="col-lg-3 col-md-3 col-sm-3 col-xs-12">
                        <div class="email_us clearfix">
                            <h6>Email us</h6>
                            <p>QTNbooking@gmail.com</p>
                        </div>
                    </div>
                    <div class="col-lg-3 col-md-3 col-sm-3 col-xs-12">
                        <div class="news_letter clearfix">
                            <input type="text" placeholder="Enter ID  for News Letter">
                            <a href="#" class="btn btn-blue">go</a>
                        </div>
                    </div>
                    <div class="col-lg-3 col-md-3 col-sm-3 col-xs-12">
                        <div class="social_icons clearfix">
                            <ul>
                                <li><a href="#"><i class="fa fa-facebook"></i></a></li>
                                <li><a href="#"><i class="fa fa-twitter"></i></a></li>
                                <li><a href="#"><i class="fa fa-google-plus"></i></a></li>
                                <li><a href="#"><i class="fa fa-linkedin"></i></a></li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </section>
        <!-- end contact us area -->
		<footer class="footer_area">
            <div class="container">
                <div class="footer">
                    <div class="footer_top padding-top-80 clearfix">
                        <div class="col-lg-4 col-md-4 col-sm-4">
                            <div class="footer_widget">
                                <div class="footer_logo">
                                    <a href="#"><img src="{% static 'hoteltp/img/footer-logo-one.png' %}" alt=""></a>
                                </div>
                                <p style="font-family: 'Fira Sans', sans-serif;"> Tập đoàn thương mại du lịch và dịch vụ QNT. </br> C.E.O: LÊ CÔNG TUỆ QUANG </p>
                                <ul>
                                    <li>
                                        <P style="font-family: 'Fira Sans', sans-serif;"><i class="fa fa-map-marker"></i>St 27 Trần Hưng Đạo, <br> Huế, Thừa Thiên Huế</P>
                                    </li>
                                </ul>
                            </div>
                        </div>
                        <div class="col-lg-4 col-md-4 col-sm-4">
                            <div class="row">
                                <div class="footer_widget clearfix">
                                    <h5 class="padding-left-15">Quick Links</h5>
                                    <div class="col-lg-6 col-md-6 col-sm-6">
                                        <ul>
                                            <li><a href="">Home</a></li>                                          
                                            <li><a href="">Facilties</a></li>
                                            <li><a href="{% url 'hotel:gallery' %}">Gallery</a></li>                                            
                                                                                      
                                        </ul>  
                                    </div>
                                    <div class="col-lg-6 col-md-6 sol-sm-6">
                                        <ul>
                                        	<li><a href="{% url 'hotel:as' %}">About us</a></li>                                                                                         
                                            <li><a href="{% url 'hotel:blog' %}">Blogs</a></li>
                                        </ul>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="col-lg-4 col-md-4 col-sm-4">
                            <div class="footer_widget">
                                <h5>We Are Global</h5>
                                <div class="footer_map">
                                    <a href="#"><img src="{% static 'hoteltp/img/footer-map-two.jpg' %}" alt=""></a>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="container">
                            <div class="footer_copyright margin-tb-50 content-center">
                                <p><i class="fa fa-copyright"></i> 2019 <a href="#">HotelQTNbooking</a>. All rights reserved</p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </footer>
        
        <script src="{% static 'hoteltp/js/vendor/jquery-1.11.2.min.js' %}"></script>
        <!-- bootstrap -->
        <script src="{% static 'hoteltp/js/bootstrap.min.js' %}"></script>
		<!-- rev slider -->
        <script src="{% static 'hoteltp/js/rev-slider/rs-plugin/jquery.themepunch.plugins.min.js' %}"></script>
        <script src="{% static 'hoteltp/js/rev-slider/rs-plugin/jquery.themepunch.revolution.js' %}"></script>
        <script src="{% static 'hoteltp/js/rev-slider/rs.home.js' %}"></script>
        <!-- uikit -->
        <script src="{% static 'hoteltp/js/uikit.min.js' %}"></script>
        <!-- easing -->
		<script src="{% static 'hoteltp/js/jquery.easing.1.3.min.js' %}"></script>
        <script src="{% static 'hoteltp/js/datepicker.js' %}"></script>
        <!-- scroll up -->
        <script src="{% static 'hoteltp/js/jquery.scrollUp.min.js' %}"></script>
        <!-- owlcarousel -->
        <script src="{% static 'hoteltp/js/owl.carousel.min.js' %}"></script>
        <!-- lightslider -->
        <script src="{% static 'hoteltp/js/lightslider.js' %}"></script>
        
        <!-- wow Animation -->
        <script src="{% static 'hoteltp/js/wow.min.js' %}"></script>
        <!--Activating WOW Animation only for modern browser-->
        <!--[if !IE]><!-->
        <script type="text/javascript">new WOW().init();</script>
        <!--<![endif]-->

        <!--Oh Yes, IE 9+ Supports animation, lets activate for IE 9+-->
        <!--[if gte IE 9]>
            <script type="text/javascript">new WOW().init();</script>
        <![endif]-->         

        <!--Opacity & Other IE fix for older browser-->
        <!--[if lte IE 8]>
            <script type="text/javascript" src="{% static 'hoteltp/js/ie-opacity-polyfill.js' %}"></script>
        <![endif]-->

        <!-- my js -->
        <script src="{% static 'hoteltp/js/main.js' %}"></script>
      </body>

Booking_Hotel_QNT/templates/hoteltp/login.html
{% extends 'hoteltp/base.html' %}
{% load static %}

{% block body %}
<body>
	{% include 'hoteltp/navbar.html' %}
<section style="padding:80px;margin-bottom:70px;background: url({% static 'hoteltp/img/hotel-facilities-bg.jpg' %}) no-repeat center center fixed;background-size:cover;">
<div style="width:40%; border-radius: 10px;margin:auto;background: rgba(255,255,255,.6);padding:40px;">
		<h4 style="margin-bottom:20px">Login</h4>
	
	<form action="" method="post">
		{% csrf_token %}
	  <div class="form-group">
	    <label style="color:#131e2a">UserName:</label>
	    <input type="text" class="form-control" name="un" placeholder="User Name"required>
	  </div>
	  <div class="form-group">
	    <label style="color:#131e2a">Password:</label>
	    <input type="password" class="form-control" name="pass" placeholder="Enter password" required>
	  </div>
	  <div class="form-group form-check">
	    <label class="form-check-label"style="color:#131e2a">
	      <input class="form-check-input" type="checkbox" required> Remember me
	    </label>
	  </div>
	  <div style="font-family: 'Playfair Display', serif;margin: 10px 0"><font color="red" >{{el}}</font></div>
	  <button type="submit" class="btn btn-primary">Submit</button>
	
	  <p style="color:#131e2a; font-family: 'Playfair Display', serif;">Bạn chưa có tài khoản?? <a href="{% url 'hotel:res' %}" style="font-family: 'Playfair Display', serif;"><b>Đăng kí</b></a> </p>
	</form>
	</div>
	</section>
{% endblock %}

Booking_Hotel_QNT/templates/hoteltp/navbar.html
 	{% load static %}
 		<!-- start preloader -->
        <div id="loader-wrapper">
            <div class="logo"><a href="#"><span>Hotel</span>-Booking</a></div>
            <div id="loader">
            </div>
        </div>
        <!-- end preloader -->
        
        <!-- start header -->
        <header class="header_area">
			<div class="header_top_area">
                <div class="container">
                    <div class="row">
                        <div class="header_top clearfix">
                            <div class="col-lg-3 col-md-3 col-sm-6 col-xs-6">
                                <div class="left_header_top">
                                    <ul>
                                        <li><a href="#" style="font-family: Arial;"><img src="{% static 'hoteltp/img/temp-icon.png' %}" alt="temp-icon">23°C HUẾ, Thừa Thiên - Huế</a></li>
                                    </ul>
                                </div>
                            </div>
                            <div class="col-lg-3 col-md-3 col-sm-6 col-xs-6 floatright">
                                <div class="right_header_top clearfix floatright">
                                    <ul class="nav navbar-nav navbar-right">
                                        {% if user.is_authenticated %}
                                        <li class="">   
                                            <a class="border-right-dark-4" href="#">XIN CHÀO, {{user.username}}</a></li>
                                        </li>
                                        <li class="">
                                        <a class="border-right-dark-4" href="{% url 'hotel:logout' %}">Logout</a></li>
                                         </li>
                                        {% endif %}
                                    </ul>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <!-- start main header -->
            <div class="main_header_area">
                <div class="container">
                    <!-- start mainmenu & logo -->
                    <div class="mainmenu">
                        <div id="nav">
                            <nav class="navbar navbar-default">
                                <!-- Brand and toggle get grouped for better mobile display -->
                                <div class="navbar-header">
                                  <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                                    <span class="sr-only">Toggle navigation</span>
                                    <span class="icon-bar"></span>
                                    <span class="icon-bar"></span>
                                    <span class="icon-bar"></span>
                                  </button>
                                  <div class="site_logo fix">
                                      <a id="brand" class="clearfix navbar-brand border-right-whitesmoke" href="{% url 'hotel:index' %}"><img src=" {% static 'hoteltp/img/site-logo.png' %}" alt="Trips"></a>
                                  </div>
                                </div>

                                <!-- Collect the nav links, forms, and other content for toggling -->
                                <div class="collapse navbar-collapse navbar-right" id="bs-example-navbar-collapse-1">
                                  <ul class="nav navbar-nav">
                                    <li role="presentation">
                                        <a href="{% url 'hotel:index' %}">
                                          Home
                                        </a>
                                    </li>        
                                    <li><a href="{% url 'hotel:gallery' %}">Gallery</a></li>
                                    <li role="presentation" class="dropdown">
                                        <a id="drop2" href="#" class="dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" role="button" aria-expanded="false">
                                          Features
                                        </a>
                                        <ul id="menu2" class="dropdown-menu" role="menu">
                                          <li role="presentation"><a role="menuitem" tabindex="-1" href="{% url 'hotel:as' %}">About US</a></li>
                                          <li role="presentation"><a role="menuitem" tabindex="-1" href="{% url 'hotel:booking' %}">Booking</a></li>
                                          <li role="presentation"><a role="menuitem" tabindex="-1" href="{% url 'hotel:404' %}">404 Page</a></li>
                                        </ul>
                                    </li>
                                    <li><a href="{% url 'hotel:blog' %}">Blogs</a></li>
                                  </ul>
                                  <div class="emergency_number">
                                      <a href="tel:0123456789" style="margin-right: 8px"><img src="img/call-icon.png" alt="">012 345 6789</a>
                                  </div>
                                </div><!-- /.navbar-collapse -->
                            </nav>
                        </div>
                    </div>
                    <!-- end mainmenu and logo -->
                </div>
            </div>
            <!-- end main header -->

        </header>
        <!-- end header -->

Booking_Hotel_QNT/templates/hoteltp/res.html
{% extends 'hoteltp/base.html' %}
{% load static %}

{% block body %}
<body>
{% include 'hoteltp/navbar.html' %}
<section style="padding:40px;margin-bottom:70px;background: url({% static 'hoteltp/img/natura.jpg' %}) no-repeat center center;background-size:cover;">

<div style="width:40%;border-radius:10px;margin:auto;background: rgba(255,255,255,.5);padding:40px;">
	<h4 style="margin-bottom: 20px">Register</h4>
	  <form method="post" action="" class="form-qnt">
	    {% csrf_token %}
	    <div style="font-family: 'Playfair Display', serif;margin:10px 0;font-size: 18px"><font style="color:#ffb100">{{kt}}</font></div>
	    <div class="form-group">
		  {{form.as_p}}
	     </div>
	  	<div style="">
		    <button type="submit" class="btn btn-primary">Submit</button>
		   	<a style="margin-left: 40px;color: white;background: rgba(36, 37, 42, .5);font-size: 17px; text-decoration: none; padding-left: 30px;padding-right: 30px" class="btn btn-link" href="{% url 'hotel:login' %}">Back</a> </p>
	   </div>
	  </form>
	 </div>
  </section>
{% endblock %}